trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    connectedServiceName: 'rg-api-board-dev-connection'
    location: germanywestcentral
    resourceGroupName: rg-api-board-dev
    csmFile: deploy_infrastructure.bicep
    overrideParameters: >
        -appName fn-rg-api-board-dev


