trigger: none
#- main

pool:
  vmImage: ubuntu-latest

variables:
  ResourceGroupName: rg-api-board-dev
  DeploymentDefaultLocation: germanywestcentral
  AppName: fn-api-board-dev

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    connectedServiceName: rg-api-board-dev-connection
    resourceGroupName: $(ResourceGroupName)
    location: $(DeploymentDefaultLocation)   
    csmFile: deploy_infrastructure.bicep
    overrideParameters: >
        -appName $(AppName)


