name: Infrastructure
on:
  workflow_call:
  workflow_dispatch:
jobs:
  build-infrastructure-job:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@main
        - uses: azure/login@v1
          with: 
            creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}
        - name: deploy
          uses: azure/arm-deploy@v1
          with:
            subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
            resourceGroupName: ${{ secrets.AZURE_RG }}
            template: ./deploy_infrastructure.bicep
            parameters: 'appName=${{ vars.AZURE_FUNCTIONAPP_NAME }}'
            failOnStdErr: false